config/routes.rb
AppUits::Application.routes.draw do
  resources :investments

  resources :users

  root 'users#index'
  post 'users/new'

  post 'users/login'
  
  post 'investments/edit'

  get 'investments/show'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :investments, dependent: :destroy
	validates :name,    :presence => true,		on: :login
    validates :password,:presence => true,		on: :login                    
	validates :total_amount,   :presence => true
	validates :salary,     :presence => true
    validates :type,    :presence => true
   #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_user=User.find(session[:user_id])
    puts "this is id #{@user.id}"
  end

  # GET /users/new
  def new
    @user = User.new
    #@manager= Manager.new
    #@developer= Developer.new
    #@lead= Lead.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    #raise params.inspect
    #@user = User.new(user_params)
    if params["user"]["type"]=="manager"
      @manager= Manager.create(name:params[:user][:name], password:params[:user][:password], salary:params[:user][:salary],total_amount:params[:user][:total_amount])
      #puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      respond_to do |format|
        if @manager.save
          format.html { redirect_to users_path, notice: 'User was successfully created.' }
          format.json { render action: 'show', status: :created, location: @manager }
        else
          format.html { render action: 'new' }
          format.json { render json: @manager.errors, status: :unprocessable_entity }
        end
      end

    elsif params["user"]["type"]=="lead"
          @lead= Lead.create(name:params[:user][:name], password:params[:user][:password], salary:params[:user][:salary],total_amount:params[:user][:total_amount])
          respond_to do |format|
            if @lead.save
              format.html { redirect_to users_path, notice: 'User was successfully created.' }
              format.json { render action: 'show', status: :created, location: @lead }
            else
              format.html { render action: 'new' }
              format.json { render json: @lead.errors, status: :unprocessable_entity }
            end
          end

      else params["user"]["type"]=="developer"
        @developer= Developer.create(name:params[:user][:name], password:params[:user][:password], salary:params[:user][:salary],total_amount:params[:user][:total_amount])
        respond_to do |format|
          if @developer.save
            format.html { redirect_to users_path, notice: 'User was successfully created.' }
            format.json { render action: 'show', status: :created, location: @developer }
          else
            format.html { render action: 'new' }
            format.json { render json: @developer.errors, status: :unprocessable_entity }
          end
        end
      end
    
    puts "<<<<<<<<<<<<<<<<< #{params[:user][:type]}"
  end
          
  def login
    
    if @user=User.find_by_name_and_password(params[:name],params[:password])
      session[:user_id]=@user.id
      #puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      redirect_to user_path(@user)
    else
      puts "Check your details again!"
            redirect_to user_path(@user)

    end
    
   
    #redirect_to user_path
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:password, :type, :salary, :total_amount)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @manager=User.new do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%#= @user.error %>
 
   <fieldset><center>
  <br><div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.number_field :password %>
  </div>
  <div class="field">
    <%= f.label :salary %>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :total_amount %>
    <%= f.number_field :total_amount %>
  </div>
  <div class="dropdown">
    <%= f.select :type, options_for_select(%w[manager lead developer]) %>
    </div><br><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %></center>
</fieldset>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%#= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<br>
<center><h1><u>Welcome to User Investment Tracking System</u></h1><center>
<br>
<p><h3>This website is about keeping track of user's financial transactions. We provide a suitable view of every user, allowing them to have control over what is their profiles. Every user has various details like his salary, his investment records etc. </h3></p>

<fieldset>
  <%= form_tag(:action=>'login') do %>
<h2>Members Login</h2>
<%= label_tag(:name,    "Name:  ") %>
  <%= text_field_tag(:name) %>
 <br>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  <br>
  <%= submit_tag 'login'%>
  
  
  <%#= button_to "Logout" , {:controller =>"users" ,:action=> "logout" },:method => 'post' %>
<% end %>
<h2>New User? Sign Up here </h2>
<%= button_to "New User", new_user_path%>
</fieldset>

app/views/users/loginpage.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<center><%= link_to 'Back', users_path %><center>

app/views/users/show.html.erb
<br>
<center><h2>Welcome <%= @current_user.name %></h2></center>
<fieldset>
	<center>
<h3>Your current Account Details are </h3>
<h3><p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
	<strong>Role</strong>
	<%= @user.type %>
</p>

<!-- <p>
	<strong>Month wise investment</strong>
	<%= @user.type %>
</p>

<p>
  <strong>Total Investment:</strong>
  <%= @user.salary %>
</p> -->

<p>
  <strong>Total amount:</strong>
  <%= @user.total_amount %>
</p>
<p>
  <strong>Salary:</strong>
  <%= @user.salary %>
</p>
<p>
  <strong>Total Investment:</strong>
  <%= @user.investments.map{|e|e.total_inv} %>
</h2>
<%= link_to 'Edit', edit_user_path(@user) %><br>
<%= link_to 'Investments', investments_path , id: @user.id %><br>

<%= link_to 'Logout', users_path %>
</center></fieldset>